### ISSUE TITLE
Intermingles 'sold' and 'watching'

### ISSUE THREAD

**Issue by ppriest** [eladnava/ebay-popularity-sort#6]
ebay lists only the sold or watching count per item. This extension sorts by the numeric count regardless.
Given there's only one or other in the page content, not clear how this could be resolved, but still it doesn't behave as advertised so imho worthy of mention.

**Comment by eladnava** [comment]
Thanks for the report @ppriest, this has been fixed in https://github.com/eladnava/ebay-popularity-sort/commit/cb594d903b739de491bb1368b0ac3fc491b209ac.

**Comment by ppriest** [comment]
@eladnava
Note that it's not fixed in the sense that it will now appear sanely ordered, but items showing 'watching' do not show the sold count, and are not ranked where they would be of they did.
Ebay will sometimes choose to show the 'watched' metric, in place of 'sold'. This does not mean sold==0 (or even watching > sold, not sure of the precise algo).

**Comment by eladnava** [comment]
Hi @ppriest,
You are right, however, there is no easy way for us to fetch the item sold count in this case since it is not available in the search results page, only within the actual item page. 

We would need to execute a web request to each item page in order to fetch the sold count and this could take a lot of time for several items with a watched indicator.
